apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-api-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: todo-api
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http        
      path: /metrics
      interval: 15s
