apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-ui
  labels:
    app: metrics-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-ui
  template:
    metadata:
      labels:
        app: metrics-ui
    spec:
      containers:
      - name: metrics-ui
        image: metrics-ui:latest
        imagePullPolicy: Never

